#!/usr/bin/env python

"""\
Each new term in the Fibonacci sequence is generated by adding 
the previous two terms. By starting with 1 and 2, the first 10 
terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values 
do not exceed four million, find the sum of the even-valued terms.
"""

fibs = []
def fibonacci(term, prev):
    fibs.append(prev)
    if term>4000000:
        return prev
    else:
        return fibonacci(term+prev, term)

def fibonacci2(limit):
    term, prev = 2, 1
    sum = 0
    while prev<=limit:
        if term%2==0:
            sum += term
        term, prev = term + prev, term
    return sum

if __name__=="__main__":
    term, prev = 2, 1
    fibonacci(term, prev)
    print(sum([i for i in fibs if i%2==0]))
    print(fibonacci2(4000000))
